### ISSUE TITLE
Kosit validator Xrechnung 2.2

### ISSUE THREAD

**Issue by raji-hs** [ITSGGMBH/validator-configuration-diga#5]
Hallo zusammen,
![Report](https://github.com/ITSGGMBH/validator-configuration-diga/assets/28503134/31ffd60f-4459-4a5f-8a62-135a45675d39)
Beim Validierung von xrechnung 2.2.0 haben wir folgende Fehler bekommen: `""http://www.xoev.de/de/validator/framework/1/scenarios":customLevel" darf maximal "3"-mal in der aktuellen Abfolge auftreten. Dieser Grenzwert wurde überschritten. An dieser Stelle wird kein untergeordnetes Element erwartet.`

Ich sehe in `scenarios.xml ` file, dass mehr als 3 `customLevel` konfiguriert sind. 

```
      <customLevel level="information">BR-CL-01</customLevel>
      <customLevel level="warning">BR-CL-23</customLevel>
      <customLevel level="information">BR-CL-21</customLevel>
      <customLevel level="information">BR-CL-11</customLevel>
      <customLevel level="information">BR-CL-10</customLevel>
      <customLevel level="information">BR-CL-25</customLevel>
      <customLevel level="information">BR-CL-26</customLevel>
```

Gibt es dafür ein Workaround ?

**Comment by rboitsg** [comment]
Hi!

Das ist interessant. Ein Problem mit den Reports war mir bisher nicht bekannt. Danke für die Info!

Da scheint das Schema nicht zu den Gegebenheiten zu passen. Allerdings nicht nur bei dieser Konfiguration, so wie ich das sehe.
Als Beispiel: Die Prüfregeln für XRechnung von KoSIT (genauer: die [scenarios.xml](https://github.com/itplr-kosit/validator-configuration-xrechnung/blob/master/scenarios.xml)) definieren ebenfalls mehr als drei CustomLevels während [das Report Schema](https://github.com/itplr-kosit/validator-configuration-xrechnung/blob/master/src/report.xsd) dort auch auf maximal drei CustomLevel eingestellt ist.

[Seit spätestens 2020-12-21](https://github.com/itplr-kosit/validator/commit/705d31fdc81dae750af4d23ce2253aca30d3729b) sind mit dem KoSIT Validator mehr als drei CustomLevel erlaubt. Ich gehe davon aus, dass das Report Schema in Vergessenheit geraten ist. (Scheinbar überall)

Ein schneller Workaround wäre wohl die maximale Anzahl im Report Schema auf `unbounded` zu stellen. Ich schau, dass ich diese Woche aber noch das hier im Repository nachziehe und 1-2 Test hierfür hinzufüge.

**Comment by rboitsg** [comment]
Änderungen sind nun auf dem main Branch. Wenn die Änderung das Problem löst, kann ich auch einen neuen Release erstellen.
