### ISSUE TITLE
EDFC0 V3 Validierung schlägt fehl, auch wenn Diga 5.0.0 die Daten akzeptiert.

### ISSUE THREAD

**Issue by vstoppe** [ITSGGMBH/validator-configuration-diga#7]
Hallo zusammen,
ich habe gerade den Validator mit einem ActivationCode getestet, der schon funktionierte, bekam aber eine Ablehnung. Es hat für mich den Anschein, dass der Validator nicht sauber gegen EDFC0 V3 testet.

Eckdaten:
- Erfolgreicher Test gegen DiGA: 5.0.0
- Ablehnung mit:  validationtool-1.5.0-standalone.jar (Configuration for transitional period 2023-10-01 to 2023-12-31 (bugfix))

Input:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Pruefung_Freischaltcode version="003.000.000" gueltigab="2022-08-25" absender="123456789" empfaenger="102114819" nachrichtentyp="ANF" verfahrenskennung="TDFC0" xmlns="http://www.gkv-datenaustausch.de/XML-Schema/EDFC0_Pruefung/1.0">
    <Anfrage>
       <IK_DiGA_Hersteller>123456789</IK_DiGA_Hersteller>
        <IK_Krankenkasse>102114819</IK_Krankenkasse>
        <DiGAID>00300</DiGAID>
        <Freischaltcode>1234567890ABCDEF</Freischaltcode>
    </Anfrage>
</Pruefung_Freischaltcode>
```
(Diga-Herstelle/-absender und AC/Freischaltcode musste ich anonymisieren.)

Diga hat auf diese Anfrage folgende positive Antwort geschickt:
```xml
<?xml version="1.0"?>
<Pruefung_Freischaltcode xmlns="http://www.gkv-datenaustausch.de/XML-Schema/EDFC0_Pruefung/3.0" nachrichtentyp="ANT" verfahrenskennung="EDFC0" absender="102110939" empfaenger="102114819" version="003.000.000" gueltigab="2022-08-25"><Antwort><IK_DiGA_Hersteller>123456789</IK_DiGA_Hersteller><IK_Krankenkasse>102114819</IK_Krankenkasse><DiGAVEID>00300001</DiGAVEID><Freischaltcode>1234567890ABCDEF</Freischaltcode><Tag_der_Leistungserbringung>2023-08-08</Tag_der_Leistungserbringung></Antwort></Pruefung_Freischaltcode>
```

Der Validator reagiert auf diese Daten mit folgender Ablehnung:

```bash
$ java -jar lib/validationtool-1.5.0-standalone.jar -h -s build/config/scenarios.xml -r build/config/ -o build/test ~/scripts/check_diga/activationcodes/nds_ac_Invirto.xml
KoSIT Validator version 1.5.0
Loading scenarios from  file:///home/vst/tmp/validator-configuration-diga/build/config/scenarios.xml
Using repository  file:///home/vst/tmp/validator-configuration-diga/build/config/

Loaded "DiGA-Konfiguration für den KoSIT Validator" by ITSG GmbH from 2023-04-28 
The following scenarios are available:
  * DiGA Freischaltcode (DFC0), Version 2.0.0
  * DiGA Freischaltcode (DFC0), Version 3.0.0
  * DiGA-Rechnung (DRE0-Anfrage) 2023-04-28 basierend auf EN16931 CIUS XRechnung 2.0.0 (UN/CEFACT CII 100.D16B)
  * DiGA-Rechnung (DRE0-Anfrage) 2023-04-28 basierend auf EN16931 CIUS XRechnung 2.2.0 (UN/CEFACT CII 100.D16B)
  * Prüfbericht für DiGA-Rechnung (DRE0-Antwort)
  * DiGA-Verzeichnis, Version 2.1.0 (DVZ0)
  * Kostenträger Mappingverzeichnis (DRE0-MVZ), Version 2.0.0
  * Kostenträger Mappingverzeichnis (DRE0-MVZ), Version 3.0.0


Processing of 1 objects started
Processing of 1 objects completed in 97ms
Results:
----------------------------------------------------------------------------------------------------------------
|File                                                        |Schema |Schematron|Acceptance|Error/Description   |
|/home/vst/scripts/check_diga/activationcodes/nds_ac_...|   N   |    Y     |  REJECT  |                    |
|irto.xml                                                    |       |          |          |                    |
----------------------------------------------------------------------------------------------------------------
Acceptable:  0  Rejected:  1


##############################
#     Validation failed!     #
##############################
```

Mache ich etwas falsch oder der Validator? Ich wollte mit dem Tool demnächst auch Xrechnung 2.2 XMLs testen.

**Comment by rboitsg** [comment]
Hi!

Der Validator (im Zusammenspiel mit der Konfiguration) ist sehr streng. In diesem Fall schlägt die Schemavalidierung fehl.
Genauer gesagt, kann kein Szenario für die Validierung ermittelt werden.

Das Szenario wird auf Basis der angegeben Version ermittelt. In diesem Fall `/dfc0:Pruefung_Freischaltcode[@version="003.000.000"]`. Das Präfix `dfc0` wird üblicherweise in den XML Dateien nicht extra erwähnt, da es der Default-Namespace ist. Und hier liegt nun der Unterschied:

* `http://www.gkv-datenaustausch.de/XMLSchema/EDFC0-basis/3.0` wird erwartet
* `http://www.gkv-datenaustausch.de/XML-Schema/EDFC0_Pruefung/1.0` ist im angegebenen Beispiel festgelegt

In diesem Fall würde ich sogar sagen, dass beide Angaben falsch sind (siehe [DiGA-Abrechnungsschema (XSD) vom 24.05.2022](https://www.gkv-datenaustausch.de/media/dokumente/leistungserbringer_1/digitale_gesundheitsanwendungen/technische_anlagen_aktuell_7/DiGA-Abrechnungsschema_XSD_V3.0.0_20220524.zip)). Erwartet wird die Basis, obwohl es das "Pruefung" Schema gibt. Scheinbar ist das zuvor niemandem aufgefallen.

Richtig sollte es also heißen: `http://www.gkv-datenaustausch.de/XML-Schema/EDFC0_Pruefung/3.0`.

Ich schaue, dass frühestmöglich eine Korrektur hierfür veröffentlicht wird.

**Comment by rboitsg** [comment]
Hi!

Ich konnte den Bugfix für den Release im Januar einpflegen.

Die Prüfung des Namespace wurde korrigiert und entsprechende Tests hinzugefügt.

Damit sollte das Problem behoben sein.
